[package]
name = "necs_internal"
version = "0.1.0"
edition = "2024"

[dependencies]
slotmap = "1.0.7"
foldhash = "0.2.0"
necs_macros = { path = "../necs_macros" }

[dev-dependencies]
necs = { path = "../" }
