[package]
name = "necs_internal"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = "0.16.1"
slotmap = "1.0.7"
rustc-hash = "2.1.1"
necs_macros = { path = "../necs_macros" }

[dev-dependencies]
necs = { path = "../" }
