[package]
name = "necs_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["visit"] }
proc-macro2 = "1.0"

[dev-dependencies]
necs = { path = "../" }

[lib]
proc-macro = true
